### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[52, 20, 93,  6],
       [49,  3, 51, 57],
       [ 1, 73, 89, 81],
       [48, 59, 73, 28],
       [56, 99, 98, 45],
       [17, 97, 81, 36]])

In [ ]:
np.sort(a)[::-1]

array([98, 91, 90, 77, 58, 55, 49, 47, 34, 33, 27, 20, 18, 16, 16])

In [ ]:
np.sort(b,axis=0)

array([[ 1,  3, 51,  6],
       [17, 20, 73, 28],
       [48, 59, 81, 36],
       [49, 73, 89, 45],
       [52, 97, 93, 57],
       [56, 99, 98, 81]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 49,  77,  16,  55,  16,  34,  47,  18,  27,  90,  20,  91,  33,
        58,  98, 200])

In [ ]:
b

array([[52, 20, 93,  6],
       [49,  3, 51, 57],
       [ 1, 73, 89, 81],
       [48, 59, 73, 28],
       [56, 99, 98, 45],
       [17, 97, 81, 36]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[52.        , 20.        , 93.        ,  6.        ,  0.9083009 ],
       [49.        ,  3.        , 51.        , 57.        ,  0.24839849],
       [ 1.        , 73.        , 89.        , 81.        ,  0.72546868],
       [48.        , 59.        , 73.        , 28.        ,  0.12294231],
       [56.        , 99.        , 98.        , 45.        ,  0.3711012 ],
       [17.        , 97.        , 81.        , 36.        ,  0.26547412]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape9

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[49],
       [77],
       [16],
       [55],
       [16],
       [34],
       [47],
       [18],
       [27],
       [90],
       [20],
       [91],
       [33],
       [58],
       [98]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  9, 11, 13, 14]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([49,  0, 16,  0, 16, 34, 47, 18, 27,  0, 20,  0, 33,  0,  0])

In [ ]:
np.where(a%2 == 0,0,a)

array([49, 77,  0, 55,  0,  0, 47,  0, 27,  0,  0, 91, 33,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.argmax(a)

np.int64(14)

In [ ]:
b

array([[52, 20, 93,  6],
       [49,  3, 51, 57],
       [ 1, 73, 89, 81],
       [48, 59, 73, 28],
       [56, 99, 98, 45],
       [17, 97, 81, 36]])

In [ ]:
np.argmax(b,axis=0)

array([4, 4, 4, 2])

In [ ]:
np.argmax(b,axis=1)

array([2, 3, 2, 2, 1, 1])

In [ ]:
# np.argmin
np.argmin(a)

np.int64(2)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.cumsum(a)

array([ 49, 126, 142, 197, 213, 247, 294, 312, 339, 429, 449, 540, 573,
       631, 729])

In [ ]:
b

array([[52, 20, 93,  6],
       [49,  3, 51, 57],
       [ 1, 73, 89, 81],
       [48, 59, 73, 28],
       [56, 99, 98, 45],
       [17, 97, 81, 36]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 52,  72, 165, 171],
       [ 49,  52, 103, 160],
       [  1,  74, 163, 244],
       [ 48, 107, 180, 208],
       [ 56, 155, 253, 298],
       [ 17, 114, 195, 231]])

In [ ]:
np.cumsum(b)

array([  52,   72,  165,  171,  220,  223,  274,  331,  332,  405,  494,
        575,  623,  682,  755,  783,  839,  938, 1036, 1081, 1098, 1195,
       1276, 1312])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                 49,                3773,               60368,
                   3320240,            53123840,          1806210560,
               84891896320,       1528054133760,      41257461611520,
          3713171545036800,   74263430900736000, 6757972211966976000,
       1652154110395588608, 3591218034396381184, 1451229970363875328])

In [ ]:
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.percentile(a,50)

np.float64(47.0)

In [ ]:
np.median(a)

np.float64(47.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90, 20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.flip(a)

array([98, 58, 33, 91, 20, 90, 27, 18, 47, 34, 16, 55, 16, 77, 49])

In [ ]:
b

array([[52, 20, 93,  6],
       [49,  3, 51, 57],
       [ 1, 73, 89, 81],
       [48, 59, 73, 28],
       [56, 99, 98, 45],
       [17, 97, 81, 36]])

In [ ]:
np.flip(b,axis=1)

array([[ 6, 93, 20, 52],
       [57, 51,  3, 49],
       [81, 89, 73,  1],
       [28, 73, 59, 48],
       [45, 98, 99, 56],
       [36, 81, 97, 17]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([49, 77, 16, 55, 16, 34, 47, 18, 27, 90, 20, 91, 33, 58, 98])

In [ ]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  16,  55,  16,  34,  47,  18,  27,  90,  20,  91,  33,
        58,  98])

In [ ]:
np.delete(a,[0,2,4])

array([530,  55,  34,  47,  18,  27,  90,  20,  91,  33,  58,  98])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  16,  55,  16,  34,  47,  18,  27,  90,  20,  91,  33,
        58,  98])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 55, 25, 34, 47, 25, 27, 75, 25, 75, 33, 58, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals